In [3]:
import pandas as pd

In [40]:
tickets = pd.read_csv('tickets.csv')

In [41]:
tickets.head()

,ticket_id,created,resolved,category,priority,status,assignee,channel
0,1001,2026-08-25 09:05,2026-08-29 03:34,Password reset,Low,Closed,Priya,Email
1,1002,2026-08-25 10:06,2026-08-27 21:41,Access request,Low,Closed,Priya,Portal
2,1003,2026-08-26 17:20,2026-08-28 08:58,Access request,Medium,Closed,Alex,Portal
3,1004,2026-08-27 10:40,NaN,Laptop hardware,Low,In progress,Sam,Slack
4,1005,2026-08-27 11:23,2026-08-27 15:07,Password reset,Medium,Closed,Sam,Portal

In [42]:
tickets.tail(10)

,ticket_id,created,resolved,category,priority,status,assignee,channel
240,1241,2026-10-22 14:01,2026-10-22 18:58,Access request,Medium,Closed,Priya,Slack
241,1242,2026-10-22 15:38,NaN,Password reset,Low,Open,Priya,Email
242,1243,2026-10-23 08:50,NaN,Laptop hardware,Medium,Open,NaN,Slack
243,1244,2026-10-23 09:22,2026-10-24 10:02,Password reset,Medium,Closed,Jordan,Portal
244,1245,2026-10-23 09:41,NaN,Access request,Medium,Open,NaN,Slack
245,1246,2026-10-23 09:56,2026-10-24 08:51,Password reset,Low,Closed,Alex,Portal
246,1247,2026-10-23 12:50,NaN,Password reset,Low,In progress,Alex,Slack
247,1248,2026-10-23 14:03,2026-10-24 06:15,Password reset,Medium,Closed,Alex,Slack
248,1249,2026-10-24 09:45,NaN,Password reset,Medium,Open,Alex,Slack
249,1250,2026-10-24 10:26,NaN,Access request,Low,Open,Jordan,Portal

In [39]:
tickets.describe()

         ticket_id
count   250.000000
mean   1125.500000
std      72.312977
min    1001.000000
25%    1063.250000
50%    1125.500000
75%    1187.750000
max    1250.000000

In [37]:
tickets.nunique()

ticket_id    250
created      248
resolved     220
category       8
priority       3
status         3
assignee       4
channel        3
dtype: int64

In [36]:
tickets['assignee'].nunique()

4

In [35]:
tickets.shape

(250, 8)

In [34]:
tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ticket_id  250 non-null    int64
 1   created    250 non-null    str
 2   resolved   220 non-null    str
 3   category   247 non-null    str
 4   priority   250 non-null    str
 5   status     250 non-null    str
 6   assignee   245 non-null    str
 7   channel    250 non-null    str
dtypes: int64(1), str(7)
memory usage: 31.6 KB

In [33]:
tickets["priority"].value_counts()

priority
Medium    119
Low        96
High       35
Name: count, dtype: int64

In [32]:
tickets["priority"].value_counts(normalize=True)

priority
Medium    0.476
Low       0.384
High      0.140
Name: proportion, dtype: float64

In [31]:
tickets.loc[5:10, ["ticket_id", "assignee", "priority"]]

    ticket_id assignee priority
5        1006   Jordan     High
6        1007    Priya   Medium
7        1008      Sam   Medium
8        1009     Alex      Low
9        1010    Priya   Medium
10       1011      Sam      Low

In [30]:
tickets.loc[:, "priority":"status"]

    priority       status
0        Low       Closed
1        Low       Closed
2     Medium       Closed
3        Low  In progress
4     Medium       Closed
..       ...          ...
245      Low       Closed
246      Low  In progress
247   Medium       Closed
248   Medium         Open
249      Low         Open

[250 rows x 2 columns]

In [29]:
tickets = pd.read_csv('tickets.csv')